// <auto-generated />
using System;
using Application.App.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Application.App.Persistence.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20210921002422_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Application.App.Domain.Estacion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("adminid")
                        .HasColumnType("int");

                    b.Property<string>("codigoEstacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("encargadoSeguridadid")
                        .HasColumnType("int");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("fechaMontaje")
                        .HasColumnType("datetime2");

                    b.Property<float>("latitud")
                        .HasColumnType("real");

                    b.Property<float>("longitud")
                        .HasColumnType("real");

                    b.Property<string>("municipio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("reporteid")
                        .HasColumnType("int");

                    b.Property<int?>("tecnicoid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("adminid");

                    b.HasIndex("encargadoSeguridadid");

                    b.HasIndex("reporteid");

                    b.HasIndex("tecnicoid");

                    b.ToTable("t_estaciones");
                });

            modelBuilder.Entity("Application.App.Domain.Persona", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Persona");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Persona");
                });

            modelBuilder.Entity("Application.App.Domain.Reporte", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("fechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("tecnicoEncargado")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("t_reportes");
                });

            modelBuilder.Entity("Application.App.Domain.Administrador", b =>
                {
                    b.HasBaseType("Application.App.Domain.Persona");

                    b.HasDiscriminator().HasValue("Administrador");
                });

            modelBuilder.Entity("Application.App.Domain.EncargadoSeguridad", b =>
                {
                    b.HasBaseType("Application.App.Domain.Persona");

                    b.HasDiscriminator().HasValue("EncargadoSeguridad");
                });

            modelBuilder.Entity("Application.App.Domain.TecnicoMantenimineto", b =>
                {
                    b.HasBaseType("Application.App.Domain.Persona");

                    b.HasDiscriminator().HasValue("TecnicoMantenimineto");
                });

            modelBuilder.Entity("Application.App.Domain.Estacion", b =>
                {
                    b.HasOne("Application.App.Domain.Administrador", "admin")
                        .WithMany()
                        .HasForeignKey("adminid");

                    b.HasOne("Application.App.Domain.EncargadoSeguridad", "encargadoSeguridad")
                        .WithMany()
                        .HasForeignKey("encargadoSeguridadid");

                    b.HasOne("Application.App.Domain.Reporte", "reporte")
                        .WithMany()
                        .HasForeignKey("reporteid");

                    b.HasOne("Application.App.Domain.TecnicoMantenimineto", "tecnico")
                        .WithMany()
                        .HasForeignKey("tecnicoid");

                    b.Navigation("admin");

                    b.Navigation("encargadoSeguridad");

                    b.Navigation("reporte");

                    b.Navigation("tecnico");
                });
#pragma warning restore 612, 618
        }
    }
}
